[telemenu] Fix the empty super() call not working with @staticmethod.
Switched to using class methods as `super(cls, cls)` is much shorter then `super(TeleStateMachineMenuSerialisationAdapter, TeleStateMachineMenuSerialisationAdapter)`.

This should solve:
TypeError: super(type, obj): obj must be an instance or subtype of type