[telemenu] Working on fixing the decorator problem with @classmethod — at least I reproduced the issue in the unit test now. There test_one is failing, like in telemenu.
In unit test that's burping with:
TypeError: method_one() missing 1 required positional argument: 'gnerf'

In production that's failing with:
teleflask.server.mixins.process_update:
Error executing the update listener <function ButtonMenu.on_callback_query at 0x7fdcb6b44dd0>.
Traceback (most recent call last):
  File "/telemenu_dist/example/code/src/teleflask-652cd1/teleflask/server/mixins.py", line 176, in process_update
    self.process_result(update, listener(update))  # this will be TeleflaskMixinBase.process_result()
TypeError: on_callback_query() missing 1 required positional argument: 'update'