[telemenu] Fixed classmethod decorator being at the wrong place.
This should solve `TypeError: on_callback_query() missing 1 required positional argument: 'update'`.